name: Publish Python 🐍 distribution 📦 to PyPI

on:
  push:
    branches:
      - '**'

permissions:
  id-token: write
  contents: read

env:
  PYTHON_VERSION: '3.x'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - run: pip install build
      - run: python -m build
      - uses: pypa/gh-action-pypi-publish@release/v1 
        with:
          password: ${{ secrets.PYPI_API_KEY }} 